### ISSUE TITLE
Runtime Error on Latest Release / Vortex / Skyrim Latest Version on Steam

### ISSUE THREAD

**Issue by IskanderNexus1** [hakasapl/ParallaxGen#112]
[2024-11-21 11:10:00.127] [info] Welcome to ParallaxGen version 0.7.1!
[2024-11-21 11:10:00.128] [warning] ParallaxGen is currently in ALPHA. Please file detailed bug reports on nexus or github.
[2024-11-21 11:10:00.129] [info] Loaded 2 ParallaxGen configs successfully
[2024-11-21 11:10:39.409] [info] ParallaxGen output directory: C:\ParallaxGen\ParallaxGen_Output
[2024-11-21 11:10:39.411] [info] Opening Data Folder "E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data"
[2024-11-21 11:10:39.580] [info] Deleting old output files from output directory...
[2024-11-21 11:10:39.580] [info] Initializing plugin patcher
[2024-11-21 11:10:48.860] [warning] [ParallaxGenMutagenWrapper] Referenced TXST record in Wyrmstooth.esp / 27979C / (meshes\dungeons\nordic\doors\animated\puzzledoor\_puzzledoorkeyholerusted_wt.nif, , 0) does not exist
[2024-11-21 11:10:48.861] [warning] [ParallaxGenMutagenWrapper] Referenced TXST record in LakeHaven.esp / 2F6C0C / (meshes\clutter\weaponrack\wrplaqueleft01.nif, RackFrame01:1, 1) does not exist
[2024-11-21 11:10:48.863] [warning] [ParallaxGenMutagenWrapper] Referenced TXST record in StrappyStilettos.esp / 0008B2 / (meshes\strappy stilettos\strappystilettosgnd.nif, Shoes, 0) does not exist
[2024-11-21 11:10:48.865] [warning] [ParallaxGenMutagenWrapper] Referenced TXST record in Ultimate Lingerie Collection 2.esp / 000912 / (meshes\clothes\bikini\monokini_gnd.nif, Lingerie, 0) does not exist
[2024-11-21 11:10:49.205] [critical] An unhandled exception occurred (Please provide this entire message in your bug report).

Exception type: class std::runtime_error
Message: ParallaxGenMutagenWrapper.dll:
Exception of type 'Mutagen.Bethesda.Plugins.Exceptions.RecordCollisionException' was thrown.
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.<>c__DisplayClass18_0`1.<EnumerateMajorRecords>b__1(Exception e)
   at Noggog.EnumerableExt.Catch[T](IEnumerable`1 e, Action`1 onException)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 287
   at Mutagen.Bethesda.OverrideMixIns.WinningOverrides[TMajor](IEnumerable`1 mods, Boolean includeDeletedRecords)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at ParallaxGenMutagenWrapper.PGMutagen.PopulateObjs()
Exception of type 'Mutagen.Bethesda.Plugins.Exceptions.RecordCollisionException' was thrown.
   at Mutagen.Bethesda.Plugins.Records.GroupMajorRecordCacheWrapper`1.Factory[TStream](TStream stream, ReadOnlyMemorySlice`1 data, BinaryOverlayFactoryPackage package, Int32 offset)
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryOverlay`1.SkyrimGroupFactory(OverlayStream stream, BinaryOverlayFactoryPackage package, TypedParseParams translationParams)
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryOverlay`1.<>c__DisplayClass30_0.<SkyrimGroupFactory>b__0(RangeInt64 x)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryOverlay`1.SkyrimGroupFactory(IBinaryReadStream stream, IReadOnlyList`1 locs, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryOverlay.get__Containers()
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryOverlay.get_Containers()
   at Mutagen.Bethesda.Skyrim.SkyrimModCommon.EnumerateMajorRecords(ISkyrimModGetter obj, Type type, Boolean throwIfUnknown)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Noggog.EnumerableExt.Catch[T](IEnumerable`1 e, Action`1 onException)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 285
Stack Trace:
 0# 0x00007FF733ABA699 in ParallaxGen
 1# 0x00007FF733AF605A in ParallaxGen
 2# _CxxFrameHandler4 in VCRUNTIME140_1
 3# 0x00007FF893A32572 in VCRUNTIME140_1
 4# RtlCaptureContext2 in ntdll
 5# 0x00007FF733ABE8B0 in ParallaxGen
 6# 0x00007FF733AF0CB0 in ParallaxGen
 7# BaseThreadInitThunk in KERNEL32
 8# RtlUserThreadStart in ntdll

Press ENTER to abort...

**Comment by Sebastian-81** [comment]
Will be tracked here: https://github.com/hakasapl/ParallaxGen/issues/115
