### ISSUE TITLE
Exception in ParallaxGenMutagenWrapper

### ISSUE THREAD

**Issue by Sebastian-81** [hakasapl/ParallaxGen#115]
```
[2024-11-21 13:43:41.614] [trace] [ParallaxGenMutagenWrapper] [PopulateObjs] Adding Alt Tex Reference: (meshes\elianora\modder's resources\lolicept\lolikyonuy_dweartifactbasket.nif, Basket05:0, 0) -> Eli_Breezehome.esp / 03905E
[2024-11-21 13:43:41.871] [critical] An unhandled exception occurred (Please provide this entire message in your bug report).

Exception type: class std::runtime_error
Message: ParallaxGenMutagenWrapper.dll: 
Exception of type 'Mutagen.Bethesda.Plugins.Exceptions.RecordCollisionException' was thrown.
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.<>c__DisplayClass18_0`1.<EnumerateMajorRecords>b__1(Exception e)
   at Noggog.EnumerableExt.Catch[T](IEnumerable`1 e, Action`1 onException)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 287
   at Mutagen.Bethesda.OverrideMixIns.WinningOverrides[TMajor](IEnumerable`1 mods, Boolean includeDeletedRecords)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at ParallaxGenMutagenWrapper.PGMutagen.PopulateObjs()
Exception of type 'Mutagen.Bethesda.Plugins.Exceptions.RecordCollisionException' was thrown.
   at Mutagen.Bethesda.Plugins.Records.GroupMajorRecordCacheWrapper`1.Factory[TStream](TStream stream, ReadOnlyMemorySlice`1 data, BinaryOverlayFactoryPackage package, Int32 offset)
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryOverlay`1.SkyrimGroupFactory(OverlayStream stream, BinaryOverlayFactoryPackage package, TypedParseParams translationParams)
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryOverlay`1.<>c__DisplayClass30_0.<SkyrimGroupFactory>b__0(RangeInt64 x)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryOverlay`1.SkyrimGroupFactory(IBinaryReadStream stream, IReadOnlyList`1 locs, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryOverlay.get__Containers()
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryOverlay.get_Containers()
   at Mutagen.Bethesda.Skyrim.SkyrimModCommon.EnumerateMajorRecords(ISkyrimModGetter obj, Type type, Boolean throwIfUnknown)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Noggog.EnumerableExt.Catch[T](IEnumerable`1 e, Action`1 onException)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 285
Stack Trace: 
 0# 0x00007FF7EB90B499 in ParallaxGen
 1# 0x00007FF7EB946F1A in ParallaxGen
 2# _CxxFrameHandler4 in VCRUNTIME140_1
 3# 0x00007FFB06212572 in VCRUNTIME140_1
 4# RtlCaptureContext2 in ntdll
 5# 0x00007FF7EB90F6A0 in ParallaxGen
 6# 0x00007FF7EB941AA0 in ParallaxGen
 7# BaseThreadInitThunk in KERNEL32
 8# RtlUserThreadStart in ntdll
```

Here is the link to the full log: https://www.file.io/ptLI/download/fLEu8AoGii59

Another log can be found here: https://github.com/hakasapl/ParallaxGen/issues/115

**Comment by Sebastian-81** [comment]
Culprit was the slim option of [DX - Enhanced URN](https://www.nexusmods.com/skyrimspecialedition/mods/133758?tab=description)

**Comment by Sebastian-81** [comment]
Follow up in https://github.com/hakasapl/ParallaxGen/issues/117
