### ISSUE TITLE
Abort patching

### ISSUE THREAD

**Issue by NachtSterben** [hakasapl/ParallaxGen#169]
[2024-12-24 21:53:12.298] [info] Welcome to ParallaxGen version 0.7.3!
[2024-12-24 21:53:12.298] [warning] ParallaxGen is currently in ALPHA. Please file detailed bug reports on nexus or github.
[2024-12-24 21:53:12.298] [info] Loaded 1 ParallaxGen configs successfully
[2024-12-24 21:53:13.832] [info] ParallaxGen output directory: E:\ParallaxGen\ParallaxGen_Output
[2024-12-24 21:53:13.832] [info] Opening Data Folder "E:\TES V - Skyrim SE\Data"
[2024-12-24 21:53:13.879] [info] Initializing plugin patcher
[2024-12-24 21:53:16.395] [warning] [ParallaxGenMutagenWrapper] Referenced TXST record in Eli_Breezehome.esp / 0014D4 / (meshes\furniture\blacksmithworkbench01.nif, BlacksmithWorkbench01:0, 4) does not exist
[2024-12-24 21:53:16.479] [critical] An unhandled exception occurred (Please provide this entire message in your bug report).

Exception type: class std::runtime_error
Message: ParallaxGenMutagenWrapper.dll:
Exception of type 'Mutagen.Bethesda.Plugins.Exceptions.RecordCollisionException' was thrown.
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.<>c__DisplayClass18_0`1.<EnumerateMajorRecords>b__1(Exception e)
   at Noggog.EnumerableExt.Catch[T](IEnumerable`1 e, Action`1 onException)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 289
   at Mutagen.Bethesda.OverrideMixIns.WinningOverrides[TMajor](IEnumerable`1 mods, Boolean includeDeletedRecords)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at ParallaxGenMutagenWrapper.PGMutagen.PopulateObjs()
Exception of type 'Mutagen.Bethesda.Plugins.Exceptions.RecordCollisionException' was thrown.
   at Mutagen.Bethesda.Plugins.Records.GroupMajorRecordCacheWrapper`1.Factory[TStream](TStream stream, ReadOnlyMemorySlice`1 data, BinaryOverlayFactoryPackage package, Int32 offset)
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryOverlay`1.CustomFactoryEnd(OverlayStream stream, Int32 finalPos, Int32 offset)
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryOverlay`1.SkyrimGroupFactory(OverlayStream stream, BinaryOverlayFactoryPackage package, TypedParseParams translationParams)
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryOverlay`1.<>c__DisplayClass30_0.<SkyrimGroupFactory>b__0(RangeInt64 x)
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryOverlay`1.SkyrimGroupFactory(IBinaryReadStream stream, IReadOnlyList`1 locs, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryOverlay.get__HeadParts()
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryOverlay.get_HeadParts()
   at Mutagen.Bethesda.Skyrim.SkyrimModCommon.EnumerateMajorRecords(ISkyrimModGetter obj, Type type, Boolean throwIfUnknown)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Noggog.EnumerableExt.Catch[T](IEnumerable`1 e, Action`1 onException)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 285
Stack Trace:
 0# boost_stacktrace_impl_return_nullptr in ParallaxGen
 1# boost_stacktrace_impl_return_nullptr in ParallaxGen
 2# _CxxFrameHandler4 in VCRUNTIME140_1
 3# 0x00007FFCECA62572 in VCRUNTIME140_1
 4# RtlCaptureContext2 in ntdll
 5# boost_stacktrace_impl_return_nullptr in ParallaxGen
 6# boost_stacktrace_impl_return_nullptr in ParallaxGen
 7# BaseThreadInitThunk in KERNEL32
 8# RtlUserThreadStart in ntdll

Press ENTER to abort...

**Comment by hakasapl** [comment]
This is an issue with one of your plugins. A record is using a duplicate form id
